"""Public, versioned API for CardRAG artifact producers and readers."""

from .canonical import canonical_json_bytes, canonical_sha256, sha256_bytes, sha256_chunks, sha256_file
from .cas import (
    CASPublisher,
    ImmutablePublisher,
    StablePointerPublisher,
    atomic_replace_bytes,
    atomic_replace_json,
)
from .domain import (
    ArtifactRef,
    IssuerCode,
    StrictFrozenModel,
    VerifiedArtifact,
    issuer_code,
)
from .embedding import (
    DOCUMENT_EMBEDDING_PREFIX,
    EMBEDDING_DIMENSION,
    EMBEDDING_POLICY_VERSION,
    QUERY_EMBEDDING_PREFIX,
)
from .facade import ArtifactContractError, CurrentGeneration, MCPArtifactReader
from .manifests import (
    AdoptedOCRArtifactManifest,
    EmbeddingContract,
    GenerationCounts,
    GenerationDocument,
    GenerationManifest,
    GenerationPointer,
    GenerationReady,
    LegacyAdoptionReceipt,
    LegacyAdoptionValidation,
    OCRArtifactManifest,
    OCRCacheKind,
    OCRReady,
    adopted_ocr_reuse_key,
    expected_generation_files,
)
from .ocr import (
    NativeOCRContract,
    OCRInput,
    OCRVerificationError,
    VerifiedOCR,
    native_ocr_reuse_key,
    verify_ocr_bytes,
)
from .paths import (
    STABLE_POINTER_PATH,
    GenerationPaths,
    generation_database_path,
    generation_manifest_path,
    generation_ready_path,
    generation_root_path,
    object_path,
    ocr_cache_root_path,
    ocr_manifest_path,
    ocr_ready_path,
    temporary_object_path,
    validate_identifier,
    validate_relative_path,
    validate_sha256,
)
from .secrets import SecretResolutionError, resolve_env_secret
from .settings import WebDAVSettings
from .webdav import (
    ReadOnlyWebDAVClient,
    WebDAVClient,
    WebDAVError,
    WebDAVHTTPError,
    WebDAVIntegrityError,
    WebDAVObjectStat,
    WebDAVResponse,
)

__all__ = [
    "STABLE_POINTER_PATH",
    "AdoptedOCRArtifactManifest",
    "ArtifactContractError",
    "ArtifactRef",
    "CASPublisher",
    "CurrentGeneration",
    "DOCUMENT_EMBEDDING_PREFIX",
    "EmbeddingContract",
    "EMBEDDING_DIMENSION",
    "EMBEDDING_POLICY_VERSION",
    "GenerationCounts",
    "GenerationDocument",
    "GenerationManifest",
    "GenerationPaths",
    "GenerationPointer",
    "GenerationReady",
    "ImmutablePublisher",
    "IssuerCode",
    "LegacyAdoptionReceipt",
    "LegacyAdoptionValidation",
    "MCPArtifactReader",
    "NativeOCRContract",
    "OCRArtifactManifest",
    "OCRCacheKind",
    "OCRInput",
    "OCRReady",
    "OCRVerificationError",
    "QUERY_EMBEDDING_PREFIX",
    "ReadOnlyWebDAVClient",
    "SecretResolutionError",
    "StrictFrozenModel",
    "StablePointerPublisher",
    "VerifiedArtifact",
    "VerifiedOCR",
    "WebDAVClient",
    "WebDAVError",
    "WebDAVHTTPError",
    "WebDAVIntegrityError",
    "WebDAVObjectStat",
    "WebDAVResponse",
    "WebDAVSettings",
    "adopted_ocr_reuse_key",
    "atomic_replace_bytes",
    "atomic_replace_json",
    "canonical_json_bytes",
    "canonical_sha256",
    "expected_generation_files",
    "generation_database_path",
    "generation_manifest_path",
    "generation_ready_path",
    "generation_root_path",
    "issuer_code",
    "native_ocr_reuse_key",
    "object_path",
    "ocr_cache_root_path",
    "ocr_manifest_path",
    "ocr_ready_path",
    "resolve_env_secret",
    "sha256_bytes",
    "sha256_chunks",
    "sha256_file",
    "temporary_object_path",
    "validate_identifier",
    "validate_relative_path",
    "validate_sha256",
    "verify_ocr_bytes",
]
